FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY configs/ configs/
COPY data/ data/

RUN mkdir -p models

CMD ["python", "-m", "src.train.train"]
